name: Perl CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install just
        uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: local
          key: perl-carton-${{ hashFiles('cpanfile.snapshot') }}
          restore-keys: |
            perl-carton-

      - name: Install dependencies
        run: |
          cpanm -n Carton
          just install

      - name: Run format check
        run: just fmt

      - name: Run linter
        run: just lint

      - name: Run tests
        run: just test

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
